language: python
notifications:
  email: false
services:
  - redis-server
env:
  global:
    - secure: "PTPAh8tMAhxLlnD9Aaog9oKplXC1SO+ILnCsikxD80REYpzigDaBJCm35vbD\nv9j2zZgBiKOFz4yfa0/dd3g29H47MBCO3FV5iVeHHTKHc9/+ekRsMDZ36f1C\nxd7Xsc82hJGJvGMzPp5eLIpTFzGu52usR0wleArDgqGp5jtxRC4="
    - secure: "MiAuotkGO39U3Jt9WCqXRFpneEslpHZUPu65F5NhxG5mzG9/5Z3ZSGtrnFqC\nAxbukVKUGXzNmjsaV4LROl7kRhOdc5O9++wfa0vQNOcUdXMOdu/7a/BrGyrE\nHJFHcyddlCBvwREtDua9ASZEGZrEqmjWW7n1ANedingPY0tg45k="
    - secure: "hA3hknzmAp9iieQcOphaFf+QLKanSNnuO+WLvPGECUFVkTz791MO/XFOBkAB\n7zUMbs8jS3oB6ISs0B0+AO7omoXWHFezWaR9WqZSMIZvVzGmxWiRX+KyLYN+\nruuTOK5RaiPfIkbzbTBw4yLV/kvZ2VAMiSitqIfDdWyWvJSvrCA="
    - DEBUG=true
python:
  - 2.7
install:
  - pip install -r requirements.txt -r tests/requirements.txt
script:
  - nosetests --rednose --with-cov --cov-config=.coveragerc
after_success:
  - codecov
